### ISSUE TITLE
Breaking change detected

### ISSUE THREAD

**Issue by verkaro** [RealMelkor/Gemigit#6]
I did a git pull and installed the new binary and copied the templates folder to my working server. There is some breaking change. How do I find what the reason may be or give you better feed back?

**Comment by RealMelkor** [comment]
I would need some more informations about the breaking changes, like some error messages, but if I had to guess, it may be related to changes in the database schema. Earlier, I added an update command to Gemigit that updates the database schema to the latest version of Gemigit. This command can be run by running gemigit with "update" as a command argument (typing "gemigit update" in the terminal). It would be recommended to do a backup of the database before executing this command in case something wrong happens. I will properly version Gemigit for the next updates so that breaking changes like that don't happen again without a notice.

**Comment by verkaro** [comment]
Hey thanks for info. I'll try upgrading again and get back to you with feedback. I appreciate it.

**Comment by verkaro** [comment]
All good here. Working well served from a raspberry pi on my intranet. It really is a neat server. Thanks.

Happy 4th of July, from the USA

**Comment by RealMelkor** [comment]
Thanks
